// SPDX-License-Identifier: GPL-2.0-or-later

export interface RgblightEffect {
  index: number
  name: string
  hasColorPicker: boolean
}

export const QMK_RGBLIGHT_EFFECTS: RgblightEffect[] = [
  { index: 0, name: 'All Off', hasColorPicker: false },
  { index: 1, name: 'Solid Color', hasColorPicker: true },
  { index: 2, name: 'Breathing 1', hasColorPicker: true },
  { index: 3, name: 'Breathing 2', hasColorPicker: true },
  { index: 4, name: 'Breathing 3', hasColorPicker: true },
  { index: 5, name: 'Breathing 4', hasColorPicker: true },
  { index: 6, name: 'Rainbow Mood 1', hasColorPicker: false },
  { index: 7, name: 'Rainbow Mood 2', hasColorPicker: false },
  { index: 8, name: 'Rainbow Mood 3', hasColorPicker: false },
  { index: 9, name: 'Rainbow Swirl 1', hasColorPicker: false },
  { index: 10, name: 'Rainbow Swirl 2', hasColorPicker: false },
  { index: 11, name: 'Rainbow Swirl 3', hasColorPicker: false },
  { index: 12, name: 'Rainbow Swirl 4', hasColorPicker: false },
  { index: 13, name: 'Rainbow Swirl 5', hasColorPicker: false },
  { index: 14, name: 'Rainbow Swirl 6', hasColorPicker: false },
  { index: 15, name: 'Snake 1', hasColorPicker: true },
  { index: 16, name: 'Snake 2', hasColorPicker: true },
  { index: 17, name: 'Snake 3', hasColorPicker: true },
  { index: 18, name: 'Snake 4', hasColorPicker: true },
  { index: 19, name: 'Snake 5', hasColorPicker: true },
  { index: 20, name: 'Snake 6', hasColorPicker: true },
  { index: 21, name: 'Knight 1', hasColorPicker: true },
  { index: 22, name: 'Knight 2', hasColorPicker: true },
  { index: 23, name: 'Knight 3', hasColorPicker: true },
  { index: 24, name: 'Christmas', hasColorPicker: true },
  { index: 25, name: 'Gradient 1', hasColorPicker: true },
  { index: 26, name: 'Gradient 2', hasColorPicker: true },
  { index: 27, name: 'Gradient 3', hasColorPicker: true },
  { index: 28, name: 'Gradient 4', hasColorPicker: true },
  { index: 29, name: 'Gradient 5', hasColorPicker: true },
  { index: 30, name: 'Gradient 6', hasColorPicker: true },
  { index: 31, name: 'Gradient 7', hasColorPicker: true },
  { index: 32, name: 'Gradient 8', hasColorPicker: true },
  { index: 33, name: 'Gradient 9', hasColorPicker: true },
  { index: 34, name: 'Gradient 10', hasColorPicker: true },
  { index: 35, name: 'RGB Test', hasColorPicker: true },
  { index: 36, name: 'Alternating', hasColorPicker: true },
]

export interface VialRGBEffect {
  index: number
  name: string
}

export const VIALRGB_EFFECTS: VialRGBEffect[] = [
  { index: 0, name: 'Disable' },
  { index: 1, name: 'Direct Control' },
  { index: 2, name: 'Solid Color' },
  { index: 3, name: 'Alphas Mods' },
  { index: 4, name: 'Gradient Up Down' },
  { index: 5, name: 'Gradient Left Right' },
  { index: 6, name: 'Breathing' },
  { index: 7, name: 'Band Sat' },
  { index: 8, name: 'Band Val' },
  { index: 9, name: 'Band Pinwheel Sat' },
  { index: 10, name: 'Band Pinwheel Val' },
  { index: 11, name: 'Band Spiral Sat' },
  { index: 12, name: 'Band Spiral Val' },
  { index: 13, name: 'Cycle All' },
  { index: 14, name: 'Cycle Left Right' },
  { index: 15, name: 'Cycle Up Down' },
  { index: 16, name: 'Rainbow Moving Chevron' },
  { index: 17, name: 'Cycle Out In' },
  { index: 18, name: 'Cycle Out In Dual' },
  { index: 19, name: 'Cycle Pinwheel' },
  { index: 20, name: 'Cycle Spiral' },
  { index: 21, name: 'Dual Beacon' },
  { index: 22, name: 'Rainbow Beacon' },
  { index: 23, name: 'Rainbow Pinwheels' },
  { index: 24, name: 'Raindrops' },
  { index: 25, name: 'Jellybean Raindrops' },
  { index: 26, name: 'Hue Breathing' },
  { index: 27, name: 'Hue Pendulum' },
  { index: 28, name: 'Hue Wave' },
  { index: 29, name: 'Typing Heatmap' },
  { index: 30, name: 'Digital Rain' },
  { index: 31, name: 'Solid Reactive Simple' },
  { index: 32, name: 'Solid Reactive' },
  { index: 33, name: 'Solid Reactive Wide' },
  { index: 34, name: 'Solid Reactive Multiwide' },
  { index: 35, name: 'Solid Reactive Cross' },
  { index: 36, name: 'Solid Reactive Multicross' },
  { index: 37, name: 'Solid Reactive Nexus' },
  { index: 38, name: 'Solid Reactive Multinexus' },
  { index: 39, name: 'Splash' },
  { index: 40, name: 'Multisplash' },
  { index: 41, name: 'Solid Splash' },
  { index: 42, name: 'Solid Multisplash' },
  { index: 43, name: 'Pixel Rain' },
  { index: 44, name: 'Pixel Fractal' },
]
