// SPDX-License-Identifier: GPL-2.0-or-later

/** Run state shape for a typing-test attempt, plus the pure reducers that
 *  advance it on keystrokes, backspace, and word submits. */

import type { TypingTestConfig, Quote } from './types'
import { isTimeBoundedRun } from './types'
import { type WordsForConfig, createWordsForConfigSync, refillTimeModeWords } from './word-supply'

export type TypingTestStatus = 'countdown' | 'waiting' | 'running' | 'finished' | 'paused'

/** Check if a key is a word-submit key (half-width space or full-width space). */
export function isSubmitKey(key: string): boolean {
  return key === ' ' || key === '\u3000'
}

export interface WordResult {
  word: string
  typed: string
  correct: boolean
}

export interface TypingTestState {
  status: TypingTestStatus
  /** Unique id for this run, regenerated by `freshState` on every
   *  (re)start and preserved across pause/resume. Tags analytics events
   *  so Analyze can slice a test material down to individual History
   *  runs. */
  runId: string
  words: string[]
  currentWordIndex: number
  currentInput: string
  compositionText: string
  wordResults: WordResult[]
  startTime: number | null
  endTime: number | null
  correctChars: number
  incorrectChars: number
  currentQuote: Quote | null
  wpmHistory: number[]
  /** Word indices that end a line (imported fileImport text only). At these
   *  words Enter advances; elsewhere Space advances. Empty for every other
   *  mode, so their submit behaviour is unchanged. */
  lineBreaks: Set<number>
  /** Leading whitespace per logical line (imported fileImport text, display only).
   *  Indexed by line order; empty for every other mode. */
  lineIndents: string[]
  /** Romaji keystrokes accepted so far for the current word (romajiInput
   *  mode only). Rejected keystrokes are never appended. Replayed through
   *  a fresh `createRomajiMatcher` on every read/write instead of holding
   *  a live matcher instance, so state transitions stay pure — see
   *  `buildRomajiMatcher`. Reset to '' whenever the word advances. */
  romajiKeystrokes: string
  /** Whether the currently loaded text is romaji-capable (fileImport mode
   *  only — false for every other mode, which derive capability from
   *  `language`/`config.language` instead; see `isRomajiCapable`). Sourced
   *  from the typing-test-texts store's computed `romajiCapable` meta field
   *  and carried on `WordsForConfig` so it always reflects the text that
   *  produced `words`, never a stale value from a config/text mismatch
   *  mid-load. */
  romajiCapable: boolean
  /** Per-run tally of mistyped characters, keyed by the target character
   *  (verbatim mode — see `handleBackspace`/`handleSpace`) or the canonical
   *  romaji spelling of the mistyped kana segment (romaji mode — see
   *  `handleRomajiChar` in romaji-input.ts). Accumulates across the whole
   *  run and is never reset on word advance, only on a fresh/restarted run.
   *  Merged immutably (a new object is spread on every update). */
  mistakes: Record<string, number>
  /** Romaji mode only: true once any keystroke within the CURRENT kana
   *  segment has been rejected, until that segment completes (at which
   *  point it is tallied into `mistakes` and this resets to false). Reset
   *  on word advance / new run alongside `romajiKeystrokes`. */
  romajiSegmentErred: boolean
  /** Verbatim mode only: positions within the CURRENT word already tallied
   *  into `mistakes` via Backspace, so the word-submit pass doesn't
   *  double-count them. Reset on word advance / new run. */
  missedPositions: number[]
}

export function createInitialState(config: TypingTestConfig, language: string, status: TypingTestStatus = 'waiting'): TypingTestState {
  return freshState(createWordsForConfigSync(config, language), status)
}

export function freshState({ words, quote, lineBreaks, lineIndents, romajiCapable }: WordsForConfig, status: TypingTestStatus = 'waiting'): TypingTestState {
  return {
    status,
    runId: crypto.randomUUID(),
    words,
    currentWordIndex: 0,
    currentInput: '',
    compositionText: '',
    wordResults: [],
    startTime: null,
    endTime: null,
    correctChars: 0,
    incorrectChars: 0,
    currentQuote: quote,
    wpmHistory: [],
    lineBreaks: new Set(lineBreaks),
    lineIndents,
    romajiKeystrokes: '',
    romajiCapable,
    mistakes: {},
    romajiSegmentErred: false,
    missedPositions: [],
  }
}

export function handleChar(state: TypingTestState, char: string): TypingTestState {
  if (state.currentWordIndex >= state.words.length) return state
  return {
    ...state,
    currentInput: state.currentInput + char,
  }
}

/** If the last word is fully typed, finalize it and finish the test. */
export function tryFinishLastWord(state: TypingTestState): TypingTestState | null {
  if (state.currentWordIndex !== state.words.length - 1) return null
  const currentWord = state.words[state.currentWordIndex]
  if (state.currentInput !== currentWord) return null

  // Count chars without trailing space bonus (no space needed for last word)
  let correct = 0
  for (let i = 0; i < currentWord.length; i++) correct++

  return {
    ...state,
    currentWordIndex: state.currentWordIndex + 1,
    currentInput: '',
    wordResults: [...state.wordResults, { word: currentWord, typed: currentWord, correct: true }],
    correctChars: state.correctChars + correct,
    incorrectChars: state.incorrectChars,
    status: 'finished',
    endTime: Date.now(),
    // currentInput === currentWord here (checked above), so there is
    // nothing left to tally at submit — mistakes already recorded via
    // Backspace (if any) are carried through unchanged. Reset both
    // word-scoped mistake flags at the boundary defensively.
    missedPositions: [],
    romajiSegmentErred: false,
  }
}

/** Shared word-advance tail, run after a word has just been finalized into
 *  `base.wordResults` and `base.currentWordIndex` moved past it. Used by
 *  both the Space/Enter submit path (`handleSpace`) and the romaji
 *  auto-advance path (`handleRomajiChar`) so the time-mode word-supply
 *  refill and the words/quote finish transition stay in one place. */
export function advanceAfterWord(base: TypingTestState, config: TypingTestConfig, language: string): TypingTestState {
  const nextIndex = base.currentWordIndex

  // Time-bounded runs (monkeytype time mode, or tatoeba's Time pattern):
  // extend words if running low, never finish from words.
  if (isTimeBoundedRun(config)) {
    const refilled = refillTimeModeWords(base.words, nextIndex, config, language)
    if (!refilled) return base
    if (refilled.lineBreaks.length === 0) return { ...base, words: refilled.words }
    const lineBreaks = new Set(base.lineBreaks)
    for (const b of refilled.lineBreaks) lineBreaks.add(b)
    return { ...base, words: refilled.words, lineBreaks }
  }

  // Words and quote modes: finish when all words typed
  if (nextIndex >= base.words.length) {
    return { ...base, status: 'finished', endTime: Date.now() }
  }
  return base
}

export function handleSpace(state: TypingTestState, config: TypingTestConfig, language: string): TypingTestState {
  if (state.currentWordIndex >= state.words.length) return state

  const currentWord = state.words[state.currentWordIndex]
  const typed = state.currentInput
  const isCorrect = typed === currentWord
  const charCounts = computeWordCharCounts(currentWord, typed)
  const mistakes = applyWordMistakes(currentWord, typed, state.missedPositions, state.mistakes)

  const nextIndex = state.currentWordIndex + 1

  const base: TypingTestState = {
    ...state,
    currentWordIndex: nextIndex,
    currentInput: '',
    wordResults: [...state.wordResults, { word: currentWord, typed, correct: isCorrect }],
    correctChars: state.correctChars + charCounts.correct,
    incorrectChars: state.incorrectChars + charCounts.incorrect,
    mistakes,
    missedPositions: [],
    romajiSegmentErred: false,
  }

  return advanceAfterWord(base, config, language)
}

/** Verbatim mode's word-submit mistake pass: for every position `i` in
 *  `word` where `typed[i] !== word[i]` (a wrong char, or a char never
 *  typed at all when `typed` is shorter) and `i` is not already in
 *  `missedPositions` (already tallied at Backspace time — see
 *  `handleBackspace`), tallies one mistake keyed by the target char
 *  `word[i]`. Never counts positions beyond `word.length` (extra typed
 *  chars have no target char to attribute to). Returns `mistakes`
 *  unchanged (no allocation) when nothing new is found. */
function applyWordMistakes(
  word: string,
  typed: string,
  missedPositions: readonly number[],
  mistakes: Record<string, number>,
): Record<string, number> {
  let result = mistakes
  for (let i = 0; i < word.length; i++) {
    if (typed[i] === word[i]) continue
    if (missedPositions.includes(i)) continue
    if (result === mistakes) result = { ...mistakes }
    const key = word[i]
    result[key] = (result[key] ?? 0) + 1
  }
  return result
}

/** Verbatim mode: a Backspace that deletes a wrong character (one not
 *  matching the target word at that position) tallies one mistake keyed by
 *  the target char, immediately rather than waiting for word submit — and
 *  marks the position in `missedPositions` so the eventual submit pass
 *  (`applyWordMistakes`) doesn't double-count it even if the same wrong
 *  char is retyped and deleted again, or the word is submitted with the
 *  position still wrong. Deleting a correct char, or a char typed past the
 *  end of the word, tallies nothing. */
export function handleBackspace(state: TypingTestState): TypingTestState {
  if (state.currentInput.length === 0) return state
  const pos = state.currentInput.length - 1
  const word = state.words[state.currentWordIndex]
  let mistakes = state.mistakes
  let missedPositions = state.missedPositions
  if (word !== undefined && pos < word.length && state.currentInput[pos] !== word[pos] && !missedPositions.includes(pos)) {
    const key = word[pos]
    mistakes = { ...mistakes, [key]: (mistakes[key] ?? 0) + 1 }
    missedPositions = [...missedPositions, pos]
  }
  return {
    ...state,
    currentInput: state.currentInput.slice(0, -1),
    mistakes,
    missedPositions,
  }
}

function computeWordCharCounts(word: string, typed: string): { correct: number; incorrect: number } {
  const len = Math.max(typed.length, word.length)
  let correct = 1 // count the space separator as a correct char
  let incorrect = 0

  for (let i = 0; i < len; i++) {
    if (i < typed.length && i < word.length && typed[i] === word[i]) {
      correct++
    } else {
      incorrect++
    }
  }

  return { correct, incorrect }
}
